name: Auto Assign Issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign issue or PR
        uses: kentaro-m/auto-assign-action@v1.2.6
        with:
          configuration-path: '.github/auto_assign.yml'