name: "Auto Assign Issue Creator"

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  auto_assign_creator:
    runs-on: ubuntu-latest
    steps:
    - name: Assign issue creator as assignee
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueCreator = context.payload.issue.user.login;
          
          console.log(`Assigning issue #${context.payload.issue.number} to creator: ${issueCreator}`);
          
          await github.rest.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.issue.number,
            assignees: [issueCreator]
          });
          
          console.log(`Successfully assigned issue to ${issueCreator}`);